```{r}
dist = graph(edges = c("A", "C", "A", "B", "B", "E", "B", "F", "C", "D", "G", 'H', 'D','H','E', 'H', 'F','G'), directed = T)
plot(dist)
```
Definir Pesos
```{r}
# Pesos nas arestas que vão representar distâncias
E(dist)$weight = c(2,1,2,1,2,1,1,3,1)
plot(dist, edge.label = E(dist)$weight)
tkplot(dist, edge.label = E(dist)$weight, vertex.color="white")
```
Buscar a distância
```{r}
#calcular a distancia mais curta entre dois vertices (calcula, mas não mostra o caminho)
cat("A distância mais curta é: ",distances(dist, V(dist)$name=='A',V(dist)$name=='H'))
#Verifica no grafo
plot(dist, edge.label = E(dist)$weight)
```

```{r}
#Busca o caminho mais curto
caminho = shortest_paths(dist, V(dist)$name== "A", V(dist)$name== "H", output= "both")
caminho$vpath
plot(dist, edge.label=E(dist)$weight)

```
Destacando o caminho mais curto
```{r}
for(i in 1:length(V(dist))){
  # Se i estiver dentro do caminho será pintado de verde
  V(dist)$color[i] <- ifelse(i %in% as.vector(unlist(caminho$vpath)), 'green','gray')
}
for(i in 1:length(E(dist))){
  E(dist)$color[i] <- ifelse(i %in% as.vector(unlist(caminho$epath)), 'green','gray')
}
plot(dist, edge.label = E(dist)$weight)
```